### ISSUE TITLE
Make you first PR

### ISSUE THREAD

**Issue by pranavgoel29** [pranavgoel29/CPP-Programs#1]
After following step 1 and 2 from [CONTRIBUTING.md](CONTRIBUTING.md)

- Create an issue first with proper description and add a Hacktoberfest label to it and wait for assignment of the issue.

- Step 1 - Write any CPP program with a proper explanation.
- Step 2 - Save them in [First PR folder](https://github.com/pranavgoel29/CPP-Programs/tree/main/First%20PR)
 
DONE

- I would encourage you to make new issues if you find something worth adding.

**Comment by Yukino2002** [comment]
I would like to take this issue up.

**Comment by pranavgoel29** [comment]
> I would like to take this issue up.

Sure, you can start with your program.
You can make a separate issue, with some description about what you will be doing and I will assign it to you.

**Comment by Sriver27** [comment]
I would like to contribute with a cpp program that finds intersection between two arrays. Please can you assign it to me?

**Comment by pranavgoel29** [comment]
> I would like to contribute with a cpp program that finds intersection between two arrays. Please can you assign it to me?

Make an issue about it, I will assign it to you.

**Comment by Aryangp** [comment]
can i make a program in java

**Comment by usr-neo** [comment]
Could you assign it to me?

**Comment by pranavgoel29** [comment]
> can i make a program in java

No, sorry this is only for C++

**Comment by pranavgoel29** [comment]
> Could you assign it to me?

Make a separate issue mentioning your program and make a PR.
Add proper comments explaining the working of the line of code in the program file.
