### ISSUE TITLE
Move intersection_between_two_arrays.cpp to First PR

### ISSUE THREAD

**Issue by pranavgoel29** [pranavgoel29/CPP-Programs#11]

**Comment by Naisargika1402** [comment]
I would like to work in this. Can you please assign this to me?

**Comment by pranavgoel29** [comment]
Assigned you can work on it now.

**Comment by Naisargika1402** [comment]
Hi maintainer,
This is my first ever contribution in GitHub.
Can you please verify whether I did it correctly or not?
