### ISSUE TITLE
Kadane's Algorithm || C++

### ISSUE THREAD

**Issue by Luckshya1210** [pranavgoel29/CPP-Programs#13]
Kadane algorithm for finding the maximum sum of contiguous subarray of an array.

**Comment by Luckshya1210** [comment]
Please assign me this issue to add the code for the algorithm @pranavgoel29

**Comment by pranavgoel29** [comment]
I am sorry, but I will not be adding a particular algorithm, please read the Readme.md and create a program which will help a beginner.

**Comment by Luckshya1210** [comment]
Ok !!
