### ISSUE TITLE
All Binary tree problems

### ISSUE THREAD

**Issue by niteshkumar257** [pranavgoel29/CPP-Programs#16]
1. DFS traversal
2. BFS traversal
3. Height of the Binary Tree
4. Diameter of the Binary Tree
5. Zig-zag traversal of the Binary Tree
6. Boundary Traversal of the Binary Tree
7. Right_view of the Binary Tree
8. Left_view of the Binary Tree
9. Minimum time to burn the Binary Tree
10. Max root to leaf path sum

**Comment by niteshkumar257** [comment]
please assign this to me

**Comment by pranavgoel29** [comment]
Not taking problem solutions.

**Comment by niteshkumar257** [comment]
Then can I contribute different concept algorithms

**Comment by pranavgoel29** [comment]
Try to explain concepts with programs, eg - pointers
