### ISSUE TITLE
reverse linked list

### ISSUE THREAD

**Issue by sunidhisachan** [pranavgoel29/CPP-Programs#20]

**Comment by sunidhisachan** [comment]
@pranavgoel29 please add the label and assign this to me.

**Comment by pranavgoel29** [comment]
Sorry, as of now won't be adding advance topics.

**Comment by sunidhisachan** [comment]
> Sorry, as of now won't be adding advance topics.

should i edit this issue and add some simpler topic?

**Comment by pranavgoel29** [comment]
Yes, if you want to you can. 👍
