### ISSUE TITLE
Sort 0,1 

### ISSUE THREAD

**Issue by Sriver27** [pranavgoel29/CPP-Programs#9]

**Comment by Sriver27** [comment]
@pranavgoel29 please assign it to me

**Comment by pranavgoel29** [comment]
> @pranavgoel29 please assign it to me

Done, and please add proper comments for understanding the program.

**Comment by Sriver27** [comment]
@pranavgoel29 please look , I have created a pull request for the same. If there are no issues, kindly merge it. Thanks in advance.
